repos:
   - repo: local
     hooks:
        - id: dune-build-fmt
          name: dune build @fmt
          entry: dune build @fmt --auto-promote
          pass_filenames: false
          language: system
          types: [text]
        - id: dune-build-opam
          name: dune build
          entry: dune build @opam
          pass_filenames: false
          language: system
          types: [text]

   - repo: https://github.com/pre-commit/mirrors-prettier
     rev: "v3.0.3" # Use the sha or tag you want to point at
     hooks:
        - id: prettier
          types_or: [css, javascript, jsx, ts, tsx, yaml]
