name: build ambient-context

on:
   push:
      branches:
         - main
   pull_request:

jobs:
   run:
      name: build
      strategy:
         fail-fast: true
         matrix:
            os:
               - ubuntu-latest
                 #- macos-latest
                 #- windows-latest
            ocaml-compiler:
               - "4.08"
               - "4.14"
               - "5.1"

      runs-on: ${{ matrix.os }}
      steps:
         - uses: actions/checkout@main
         - name: Use OCaml ${{ matrix.ocaml-compiler }}
           uses: ocaml/setup-ocaml@v2
           with:
              ocaml-compiler: ${{ matrix.ocaml-compiler }}
              dune-cache: true
              opam-pin: false
              opam-depext: false

         - run: opam pin . -y -n
         - run: opam install -t ambient-context --deps-only
         - run: opam exec -- dune build @install --only-packages=ambient-context
         - run: opam exec -- dune runtest --only-packages=ambient-context

         # now redo it with hmap installed
         - run: opam install hmap

         - run: opam exec -- dune build @install --only-packages=ambient-context
         - run: opam exec -- dune runtest --only-packages=ambient-context
